name: pokedoku
channels:
    - conda-forge
dependencies:
    - python=3.11
    - fastapi=0.103
    - uvicorn=0.23
    - pydantic=1.10
    - python-dotenv=1
    - pip=23
    - pip:
      - pokebase==1
      - pypokedex==1

